import { FormEvent, ReactNode, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BookOpen, CheckCircle2, ChevronRight, Clock3, Edit3, FileText, FolderOpen, LogIn, LogOut, Menu, Plus, Search, ShieldCheck, Trash2, UserRound, X } from 'lucide-react';
import RichEditor from './RichEditor';

type Category = 'SOP' | 'Panduan' | 'Instruksi Kerja' | 'Safety' | 'Form & Template';
interface Article { id:string; title:string; category:Category; summary:string; content:string; author:string; updatedAt:string; readTime:number; }
const categories: Category[] = ['SOP','Panduan','Instruksi Kerja','Safety','Form & Template'];
const meta: Record<Category,{icon:typeof FileText;color:string}> = {
  SOP:{icon:FileText,color:'blue'}, Panduan:{icon:BookOpen,color:'green'}, 'Instruksi Kerja':{icon:CheckCircle2,color:'amber'},
  Safety:{icon:ShieldCheck,color:'red'}, 'Form & Template':{icon:FolderOpen,color:'purple'},
};
const seeds:Article[] = [
  {id:'inbound',title:'SOP Inbound Penerimaan Barang',category:'SOP',summary:'Prosedur penerimaan, pemeriksaan, dan penyimpanan barang masuk agar setiap pengiriman tercatat akurat.',author:'Manager Gudang',updatedAt:'2026-07-20',readTime:7,content:`<p class="lead">Panduan ini memastikan proses penerimaan barang berjalan aman, tertib, dan dapat ditelusuri sejak kendaraan tiba hingga barang masuk ke lokasi penyimpanan.</p><div class="callout"><strong>Sebelum mulai</strong><span>Pastikan purchase order, surat jalan, area staging, dan petugas pemeriksa sudah tersedia.</span></div><h2>Tujuan dan ruang lingkup</h2><p>Prosedur berlaku untuk seluruh barang dari pemasok dan transfer antargudang. Setiap penyimpangan fisik wajib dicatat maksimal 1×24 jam.</p><h2>Alur penerimaan</h2><ol><li><strong>Verifikasi jadwal.</strong> Cocokkan kendaraan dan pemasok dengan jadwal di WMS.</li><li><strong>Periksa dokumen.</strong> Pastikan nomor PO, surat jalan, jumlah koli, dan identitas pengemudi sesuai.</li><li><strong>Lakukan bongkar muat.</strong> Arahkan kendaraan ke loading dock dan amankan kendaraan.</li><li><strong>Hitung dan inspeksi.</strong> Periksa kuantitas, kemasan, serta kerusakan fisik.</li><li><strong>Label dan put away.</strong> Cetak label pallet, rekam di WMS, lalu pindahkan ke lokasi.</li></ol><h2>Checklist serah terima</h2><ul class="check-list"><li>PO dan surat jalan telah cocok</li><li>Jumlah fisik telah diverifikasi</li><li>Foto kerusakan telah dilampirkan bila ada</li><li>Label pallet dapat dipindai</li></ul>`},
  {id:'safety',title:'Panduan Keselamatan Gudang (K3)',category:'Safety',summary:'Aturan keselamatan minimum untuk karyawan, vendor, dan tamu yang memasuki area operasional gudang.',author:'HSE Coordinator',updatedAt:'2026-07-18',readTime:5,content:`<p class="lead">Keselamatan adalah syarat sebelum produktivitas. Gunakan panduan ini sebagai pemeriksaan singkat sebelum memasuki area aktif.</p><div class="callout danger"><strong>Wajib dipatuhi</strong><span>Helm, sepatu keselamatan, dan rompi reflektif harus digunakan di area operasional.</span></div><h2>Alat pelindung diri</h2><ul><li>Helm keselamatan dengan tali yang berfungsi.</li><li>Sepatu keselamatan berpelindung jari.</li><li>Rompi high-visibility yang bersih dan terlihat.</li><li>Sarung tangan sesuai jenis barang.</li></ul><h2>Jalur dan batas kecepatan</h2><p>Pejalan kaki wajib berada di jalur hijau. Forklift dibatasi 5 km/jam di loading dock dan 8 km/jam di gang utama.</p><h2>Jika terjadi insiden</h2><ol><li>Hentikan aktivitas dan amankan lokasi.</li><li>Hubungi supervisor atau petugas HSE.</li><li>Berikan pertolongan pertama sesuai kompetensi.</li><li>Catat insiden sebelum akhir shift.</li></ol>`},
  {id:'count',title:'Instruksi Kerja Cycle Count Harian',category:'Instruksi Kerja',summary:'Langkah praktis menghitung stok harian dan menangani selisih antara stok fisik dan sistem.',author:'Lead Inventory',updatedAt:'2026-07-16',readTime:4,content:`<p class="lead">Cycle count menjaga akurasi stok tanpa menghentikan seluruh operasi gudang.</p><h2>Persiapan</h2><p>Unduh daftar lokasi dari WMS, bekukan transaksi, dan siapkan pemindai barcode.</p><h2>Langkah penghitungan</h2><ol><li>Pindai lokasi dan cocokkan kode rak.</li><li>Hitung fisik tanpa melihat kuantitas sistem.</li><li>Catat lot, batch, dan kondisi barang.</li><li>Lakukan hitung ulang bila selisih lebih dari 2%.</li><li>Ajukan penyesuaian dengan bukti dan persetujuan supervisor.</li></ol>`},
  {id:'outbound',title:'Panduan Picking dan Packing Outbound',category:'Panduan',summary:'Praktik picking yang akurat dan urutan packing untuk mengurangi salah kirim serta kerusakan.',author:'Outbound Supervisor',updatedAt:'2026-07-12',readTime:6,content:`<p class="lead">Gunakan alur scan–pick–verify–pack agar barang yang benar sampai ke pelanggan yang benar.</p><h2>Picking</h2><ol><li>Pindai lokasi sebelum mengambil barang.</li><li>Cocokkan SKU, batch, dan jumlah.</li><li>Tempatkan barang pada tote sesuai gelombang picking.</li></ol><h2>Packing</h2><p>Gunakan kemasan sesuai dimensi dan karakter barang. Verifikasi berat akhir terhadap data WMS.</p>`},
  {id:'damage',title:'Form Laporan Kerusakan Barang',category:'Form & Template',summary:'Template informasi minimum untuk mendokumentasikan kerusakan dan mempercepat tindak lanjut.',author:'Quality Assurance',updatedAt:'2026-07-08',readTime:3,content:`<p class="lead">Lengkapi laporan segera setelah kerusakan ditemukan agar bukti dan konteks masih akurat.</p><h2>Data yang wajib diisi</h2><ul class="check-list"><li>Nomor SKU, batch, dan jumlah terdampak</li><li>Lokasi dan waktu penemuan</li><li>Foto keseluruhan dan detail kerusakan</li><li>Dugaan penyebab dan tindakan pengamanan</li><li>Nama pelapor dan supervisor</li></ul>`},
];
const key='warehouse-kb-v2';
const date=(v:string)=>new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'long',year:'numeric'}).format(new Date(v));
const plain=(h:string)=>h.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();

export default function App(){
 const [articles,setArticles]=useState<Article[]>(()=>{try{return JSON.parse(localStorage.getItem(key)||'null')||seeds}catch{return seeds}});
 const [active,setActive]=useState<Article|null>(null),[query,setQuery]=useState(''),[category,setCategory]=useState<Category|'Semua'>('Semua');
 const [admin,setAdmin]=useState(sessionStorage.getItem('warehouse-admin')==='true'),[modal,setModal]=useState<'login'|'editor'|null>(null),[editing,setEditing]=useState<Article|null>(null),[menu,setMenu]=useState(false),[toast,setToast]=useState('');
 useEffect(()=>localStorage.setItem(key,JSON.stringify(articles)),[articles]);
 useEffect(()=>{scrollTo({top:0,behavior:'smooth'});document.title=active?`${active.title} — Warehouse Knowledge`:'Warehouse Knowledge'},[active]);
 const filtered=useMemo(()=>articles.filter(a=>(category==='Semua'||a.category===category)&&`${a.title} ${a.summary} ${plain(a.content)}`.toLowerCase().includes(query.toLowerCase())),[articles,category,query]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2400)};
 const edit=(a?:Article)=>{setEditing(a||null);setModal('editor')};
 const remove=(a:Article)=>{if(confirm(`Hapus artikel “${a.title}”?`)){setArticles(x=>x.filter(i=>i.id!==a.id));setActive(null);notify('Artikel berhasil dihapus.')}};
 return <div className="shell">
  <header className="site-header"><div className="header-inner"><button className="brand" onClick={()=>setActive(null)}><span className="brand-mark"><BookOpen/></span><span><strong>Warehouse Knowledge</strong><small>Pusat Pengetahuan Operasional</small></span></button>
   <nav className={menu?'nav open':'nav'}><button onClick={()=>{setActive(null);setCategory('Semua')}}>Beranda</button><button onClick={()=>{setActive(null);setCategory('SOP')}}>SOP</button><button onClick={()=>{setActive(null);setCategory('Safety')}}>Keselamatan</button></nav>
   <div className="actions">{admin&&<button className="button primary desktop" onClick={()=>edit()}><Plus/>Artikel baru</button>}<button className="menu-btn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><button className="admin-btn" onClick={()=>{if(admin){setAdmin(false);sessionStorage.removeItem('warehouse-admin');notify('Mode admin dinonaktifkan.')}else setModal('login')}}>{admin?<LogOut/>:<LogIn/>}<span>{admin?'Keluar':'Admin'}</span></button></div>
  </div></header>
  {modal==='editor'?<Editor article={editing} close={()=>setModal(null)} save={a=>{setArticles(x=>editing?x.map(i=>i.id===editing.id?a:i):[a,...x]);if(active?.id===a.id)setActive(a);setModal(null);notify(editing?'Perubahan tersimpan.':'Artikel diterbitkan.')}}/>:active?<Reader article={active} related={articles.filter(a=>a.id!==active.id&&a.category===active.category)} admin={admin} back={()=>setActive(null)} open={setActive} edit={()=>edit(active)} remove={()=>remove(active)}/>:<main>
   <section className="hero"><div><span className="eyebrow">Satu sumber informasi untuk tim gudang</span><h1>Temukan jawaban.<br/><em>Kerja lebih aman dan konsisten.</em></h1><p>Akses SOP, panduan, instruksi kerja, dan formulir operasional dalam pengalaman membaca yang cepat dan mudah dipahami.</p><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari prosedur, topik, atau kata kunci…"/>{query&&<button onClick={()=>setQuery('')}><X/></button>}</label><div className="stats"><span><strong>{articles.length}</strong> artikel</span><span><strong>{categories.length}</strong> kategori</span><span><strong>24/7</strong> akses mandiri</span></div></div></section>
   <section className="content"><div className="section-title"><div><span className="eyebrow">Jelajahi pengetahuan</span><h2>Dokumen operasional</h2></div>{admin&&<button className="button primary mobile-create" onClick={()=>edit()}><Plus/>Artikel baru</button>}</div>
    <div className="filters"><button className={category==='Semua'?'active':''} onClick={()=>setCategory('Semua')}>Semua <span>{articles.length}</span></button>{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c} <span>{articles.filter(a=>a.category===c).length}</span></button>)}</div>
    <div className="results"><span>{filtered.length} artikel {query&&`untuk “${query}”`}</span>{(query||category!=='Semua')&&<button onClick={()=>{setQuery('');setCategory('Semua')}}>Reset filter</button>}</div>
    {filtered.length?<div className="grid">{filtered.map(a=><Card key={a.id} article={a} admin={admin} open={()=>setActive(a)} edit={()=>edit(a)} remove={()=>remove(a)}/>)}</div>:<div className="empty"><Search/><h3>Artikel belum ditemukan</h3><p>Coba kata kunci lain atau tampilkan semua kategori.</p><button className="button secondary" onClick={()=>{setQuery('');setCategory('Semua')}}>Tampilkan semua</button></div>}
   </section></main>}
  <footer><div><span className="brand-mark small"><BookOpen/></span><strong>Warehouse Knowledge</strong></div><p>Informasi yang tepat untuk operasi yang lebih baik.</p></footer>
  {modal==='login'&&<Login close={()=>setModal(null)} success={()=>{setAdmin(true);sessionStorage.setItem('warehouse-admin','true');setModal(null);notify('Mode admin aktif.')}}/>}
  {toast&&<div className="toast"><CheckCircle2/>{toast}</div>}
 </div>
}
function Card({article:a,admin,open,edit,remove}:{key?:string;article:Article;admin:boolean;open:()=>void;edit:()=>void;remove:()=>void}){const Icon=meta[a.category].icon;return <article className="card"><button className="card-main" onClick={open}><span className={`cat-icon ${meta[a.category].color}`}><Icon/></span><span className="category">{a.category}</span><h3>{a.title}</h3><p>{a.summary}</p><div className="card-meta"><span><Clock3/>{a.readTime} menit</span><span>{date(a.updatedAt)}</span><ChevronRight/></div></button>{admin&&<div className="card-admin"><button onClick={edit}><Edit3/>Edit</button><button onClick={remove} className="danger"><Trash2/>Hapus</button></div>}</article>}
function Reader({article:a,related,admin,back,open,edit,remove}:{article:Article;related:Article[];admin:boolean;back:()=>void;open:(a:Article)=>void;edit:()=>void;remove:()=>void}){const Icon=meta[a.category].icon;return <main className="reader-shell"><div className="reader-tools"><button onClick={back}><ArrowLeft/>Kembali ke semua artikel</button>{admin&&<div><button onClick={edit}><Edit3/>Edit</button><button onClick={remove} className="danger"><Trash2/>Hapus</button></div>}</div><article className="reader"><header><span className={`cat-icon ${meta[a.category].color}`}><Icon/></span><span className="category">{a.category}</span><h1>{a.title}</h1><p>{a.summary}</p><div className="byline"><span><UserRound/>{a.author}</span><span><Clock3/>{a.readTime} menit baca</span><span>Diperbarui {date(a.updatedAt)}</span></div></header><div className="article-body" dangerouslySetInnerHTML={{__html:a.content}}/></article>{related.length>0&&<aside className="related"><span className="eyebrow">Baca berikutnya</span><h2>Artikel terkait</h2>{related.slice(0,3).map(r=><button key={r.id} onClick={()=>open(r)}><span>{r.category}</span><strong>{r.title}</strong><ChevronRight/></button>)}</aside>}</main>}
function Frame({title,sub,close,children}:{title:string;sub:string;close:()=>void;children:ReactNode}){return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal"><button className="close" onClick={close}><X/></button><h2>{title}</h2><p>{sub}</p>{children}</section></div>}
function Login({close,success}:{close:()=>void;success:()=>void}){const [error,setError]=useState('');return <Frame title="Masuk sebagai admin" sub="Kelola dan perbarui artikel knowledge base." close={close}><form className="form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);d.get('u')==='admin'&&d.get('p')==='admin123'?success():setError('Username atau password tidak sesuai.')}}><label>Username<input name="u" defaultValue="admin" autoFocus/></label><label>Password<input name="p" type="password" defaultValue="admin123"/></label>{error&&<span className="form-error">{error}</span>}<small>Demo: admin / admin123</small><button className="button primary">Masuk</button></form></Frame>}
function Editor({article:a,close,save}:{article:Article|null;close:()=>void;save:(a:Article)=>void}){const [html,setHtml]=useState(a?.content||'<h2>Judul bagian</h2><p>Mulai tulis isi artikel Anda di sini.</p>');return <main className="editor-page"><form className="form editor-page-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget),words=plain(html).split(/\s+/).filter(Boolean).length;save({id:a?.id||String(Date.now()),title:String(d.get('title')),category:d.get('category') as Category,summary:String(d.get('summary')),author:String(d.get('author')),updatedAt:new Date().toISOString().slice(0,10),readTime:Math.max(1,Math.ceil(words/200)),content:html})}}><header className="editor-page-header"><div><button type="button" className="editor-back" onClick={close}><ArrowLeft/>Kembali</button><span className="editor-mode">Mode editor</span><h1>{a?'Edit artikel':'Buat artikel baru'}</h1><p>Susun artikel lengkap dengan teks, gambar, tautan, dan video.</p></div><div className="editor-header-actions"><button type="button" className="button secondary" onClick={close}>Batal</button><button className="button primary">{a?'Simpan perubahan':'Terbitkan artikel'}</button></div></header><section className="editor-workspace"><aside className="editor-settings"><div><span className="eyebrow">Informasi artikel</span><h2>Detail publikasi</h2></div><label>Judul<input required name="title" defaultValue={a?.title} autoFocus/></label><label>Kategori<select name="category" defaultValue={a?.category||'SOP'}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Ringkasan<textarea required name="summary" rows={5} defaultValue={a?.summary}/></label><label>Penulis<input required name="author" defaultValue={a?.author||'Tim Operasional'}/></label><div className="editor-publish-note"><CheckCircle2/><span><strong>Tersimpan di perangkat</strong>Perubahan diterapkan setelah tombol simpan ditekan.</span></div></aside><section className="editor-canvas"><div className="editor-canvas-title"><span className="eyebrow">Konten utama</span><h2>Isi artikel</h2></div><RichEditor initialHtml={html} onChange={setHtml}/></section></section><div className="editor-mobile-actions"><button type="button" className="button secondary" onClick={close}>Batal</button><button className="button primary">{a?'Simpan':'Terbitkan'}</button></div></form></main>}
